import type { NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'

const QueryOgp: NextPage = () => {
  const router = useRouter()
  const {
    title,
    emoji
  } = router.query
  console.log(title, emoji)
  return (
    <div>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>The ogp emojititle</title>
        <meta
          property="og:image"
          content={`https://kamaboko.vercel.app/api/og?title=${title}&emoji=${emoji}`}
        />
        <meta name="twitter:card" content="summary_large_image" />
      </Head>

      <div
        style={{
          background: 'linear-gradient(299deg, rgba(2,0,36,1) 0%, rgba(118,42,147,1) 23%, rgba(0,212,255,1) 100%)',
          backgroundRepeat: 'no-repeat',
          backgroundSize: 'cover',
          height: '630px',
          width: '1200px',
          display: 'flex',
          textAlign: 'center',
          alignItems: 'center',
          justifyContent: 'center',
          flexDirection: 'column',
          flexWrap: 'nowrap',
        }}
      >
        <span style={{
            fontSize: 80
          }}
        >
          {emoji}
        </span>
        <p
          style={{
            fontSize: 60,
            fontStyle: 'normal',
            letterSpacing: '-0.025em',
            color: 'white',
            marginTop: 30,
            padding: '0 120px',
            lineHeight: 1.4,
            whiteSpace: 'pre-wrap',
          }}
        >
          {title}
        </p>
      </div>
    </div>
  )
}

export default QueryOgp